# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PE0wrL3jRUhD3ZQjvzSNX-WoFEl3O2E5
"""

import random
import requests

API_URL = 'http://cryptlygos.pythonanywhere.com'

my_id = 25427   #Change this to your ID

endpoint = '{}/{}/{}'.format(API_URL, "RSA_OAEP", my_id )   
response = requests.get(endpoint) 	
c, N, e = 0,0,0 
if response.ok:	
  res = response.json()
  print(res)
  c, N, e = res['c'], res['N'], res['e']    ##get c, N, e
else: print(response.json())

########
from RSA_OAEP import RSA_OAEP_Enc
PIN_ = 0  
found = False
k0 = 8
R = 2**(k0-1)

#For each possible R try all possible PINs
while found == False:
  for m in range(1000, 10000):
    #encrypt the possible PIN with the function using R
    c_prime = RSA_OAEP_Enc(m, e, N, R)
    #if it's eqaul to ciphertext then We have found the R and PIN
    if c_prime == c:
      PIN_ = m
      print('PIN is', m)
      print('R is', R)
      found = True
      break
  R += 1
########

# Client sends PIN_ to server
endpoint = '{}/{}/{}/{}'.format(API_URL, "RSA_OAEP", my_id, PIN_)
response = requests.put(endpoint)
print(response.json())