# -*- coding: utf-8 -*-
"""411_hw3_question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQymcDNDpP6oBYT_Q7LTlGs31gf-N3OM
"""

!pip install BitVector

import random
import requests
from BitVector import BitVector

API_URL = 'http://cryptlygos.pythonanywhere.com'	#DON'T CHANGE THIS
my_id = 25427  									#ATTN: Change this into your id number

endpoint = '{}/{}/{}'.format(API_URL, "poly", my_id )
response = requests.get(endpoint) 	
a = 0
b = 0
if response.ok:	
  res = response.json()
  print(res)
  a, b = res['a'], res['b']		#Binary polynomials a and b
else:
  print(response.json())

##SOLUTION

modulus = BitVector(bitstring='100011011') 
n = 8
a_new = BitVector(bitstring= a)
b_new = BitVector(bitstring= b)
c_bitvector = a_new.gf_multiply_modular(b_new, modulus, n)
print("c is", c_bitvector)

multi_inverse = a_new.gf_MI(modulus, n)
print("multiplicative inverse of a is", multi_inverse)

#You need to calculate c and a_inv
#c = a(x)*b(x)
#a_inv is inverse of a
c = str(c_bitvector)	
a_inv = str(multi_inverse)	

##END OF SOLUTION
 

#check result of part a
endpoint = '{}/{}/{}/{}'.format(API_URL, "mult", my_id, c)
response = requests.put(endpoint) 	
print(response.json())

#check result of part b
endpoint = '{}/{}/{}/{}'.format(API_URL, "inv", my_id, a_inv)
response = requests.put(endpoint) 	
print(response.json())